[versions]
minecraft = "1.20.2"
fabric_yarn = "1.20.2+build.4"
fabric_loader = "0.15.7"
fabric_api = "0.91.6+1.20.2"
fabric_kotlin = "1.10.19+kotlin.1.9.23"
fabric_loom = "1.5-SNAPSHOT"

modmenu = "8.0.1"
yacl = "3.3.0-beta.1+1.20.2"

kaml = "0.58.0"
snakeyaml_engine_kmp = "2.7.3"

kotlin = "1.9.23"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_yarn = { module = "net.fabricmc:yarn", version.ref = "fabric_yarn" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
fabric_kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_kotlin" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
yacl = { module = "dev.isxander.yacl:yet-another-config-lib-fabric", version.ref = "yacl" }

kaml = { module = "com.charleskorn.kaml:kaml-jvm", version.ref = "kaml" }
snakeyaml_engine_kmp = { module = "it.krzeminski:snakeyaml-engine-kmp-jvm", version.ref = "snakeyaml_engine_kmp" }

[bundles]
fabric = ["fabric_loader", "fabric_kotlin"]
kaml = ["kaml", "snakeyaml_engine_kmp"]

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
