[versions]
minecraft = "1.19.4"
yarn_mappings = "1.19.4+build.1"
fabric_loader = "0.14.17"

modmenu = "6.1.0-rc.4"
clothconfig = "10.0.96"

nightconfig = "3.6.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
clothconfig = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "clothconfig" }

nightconfig_toml = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }
