[versions]
minecraft = "1.19.4"
yarn_mappings = "1.19.4+build.1"
fabric_loader = "0.14.17"
fabric_loom = "1.1-SNAPSHOT"

modmenu = "6.1.0-rc.2"
toml4j = "0.7.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
toml4j = { module = "com.moandjiezana.toml:toml4j", version.ref = "toml4j" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
