[versions]
minecraft = "1.20.2"
yarn_mappings = "1.20.2+build.4"
fabric_loader = "0.14.23"
fabric_api = "0.89.3+1.20.2"
fabric_loom = "1.3-SNAPSHOT"

modmenu = "8.0.0-beta.2"
clothconfig = "12.0.109"

nightconfig = "3.6.+"

shadow = "8.1.1"
git = "3.0.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn_mappings = { module = "net.fabricmc:yarn", version.ref = "yarn_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
clothconfig = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "clothconfig" }

nightconfig_core = { module = "com.electronwill.night-config:core", version.ref = "nightconfig" }
nightconfig_toml = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
git = { id = "com.palantir.git-version", version.ref = "git" }
