name: 🐞 Bug report
description: File a bug report
title: "bug: "
labels: [🐞 bug]
assignees: rvbsm

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: textarea
    attributes:
      label: 🔍 What happened?
      description: Please provide a clear and concise description of what happened
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🤔 What did you expect to happen?
      description: Please describe what you expected to happen.
      placeholder: Please provide a clear and concise description of what you expected to happen
    validations:
      required: true

  - type: input
    attributes:
      label: 📦 Version
      description: What version of mod are you running?
    validations:
      required: true
  - type: input
    attributes:
      label: ⛏ Minecraft Version
      description: What version of Minecraft are you using?
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📃 Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
