name: Build
on:
  push:
    branches: [ dev ]
    paths-ignore: [ "*.md" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - run: ./gradlew printVersion
        continue-on-error: true

      - run: ./gradlew chiseledBuild
      - name: Store test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/
      - uses: actions/upload-artifact@v4
        with:
          name: "1.20"
          path: versions/1.20/build/libs/*.jar
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: "1.20.2"
          path: versions/1.20.2/build/libs/*.jar
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: "1.20.5"
          path: versions/1.20.5/build/libs/*.jar
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: "1.21"
          path: versions/1.21/build/libs/*.jar
          if-no-files-found: error
