name: Build
on:
  push:
    branches: [ dev ]
    paths-ignore: [ "*.md" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - run: ./gradlew chiseledBuild
      - name: Store test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/
      - uses: actions/upload-artifact@v4
        with:
          name: "fsit artifacts"
          path: build/libs/*.jar
          if-no-files-found: error
