name: Build
on:
  push:
    branches: [dev]
    paths-ignore: ["*.md"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - run: ./gradlew chiseledBuild --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: 1.20.1
          path: versions/1.20.1/build/libs/*.jar
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: 1.20.2
          path: versions/1.20.2/build/libs/*.jar
          if-no-files-found: error
