name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - run: ./gradlew build
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          loaders: |
            fabric
            quilt
          game-versions: |
            1.16
            1.16.1
            1.16.2
            1.16.3
            1.16.4
            1.16.5
            1.17
            1.17.1
            1.18
            1.18.1
            1.18.2
            1.19
            1.19.1
            1.19.2
            1.19.3
          dependencies:
            modmenu | suggests | *

          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: J5NAzRqK

          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-id: 837056
