name: Release
on:
  tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - run: ./gradlew build
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          name: ""
          loaders: |
            fabric
            quilt
          dependencies:
            modmenu | optional | *

          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: J5NAzRqK
          modrinth-featured: true

          github-token: ${{ secrets.GITHUB_TOKEN }}
